<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class KbliSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            [
                'nama' => 'PEST CONTROL',
                'kode' => '81290',
                'ruang_lingkup' => 'Jasa Pengendalian Hama (Pest Control)',
                'dinas_id' => 2,
                'kategorikbli_id' => 14,
            ],
            [
                'nama' => 'RUMAH SAKIT PEMERINTAH KELAS C DAN D',
                'kode' => '86101',
                'ruang_lingkup' => 'Rumah Sakit Pemerintah Kelas C dan D',
                'dinas_id' => 2,
                'kategorikbli_id' => 17,
            ],
            [
                'nama' => 'APOTEK',
                'kode' => '47721',
                'ruang_lingkup' => 'Perdagangan Eceran Produk Farmasi',
                'dinas_id' => 2,
                'kategorikbli_id' => 8,
            ],
            [
                'nama' => 'TOKO OBAT',
                'kode' => '47722',
                'ruang_lingkup' => 'Perdagangan Eceran Obat',
                'dinas_id' => 2,
                'kategorikbli_id' => 8,
            ],
            [
                'nama' => 'SELURUH PUSKESMAS',
                'kode' => '86102',
                'ruang_lingkup' => 'Pusat Kesehatan Masyarakat (Puskesmas)',
                'dinas_id' => 2,
                'kategorikbli_id' => 17,
            ],
            [
                'nama' => 'RUMAH SAKIT SWASTA KELAS C DAN D',
                'kode' => '86103',
                'ruang_lingkup' => 'Pelayanan Kesehatan Rumah Sakit Swasta Kelas C dan D',
                'dinas_id' => 2,
                'kategorikbli_id' => 17,
            ],
            [
                'nama' => 'KLINIK PRATAMA PEMERINTAH DAN KLINIK UTAMA PEMERINTAH',
                'kode' => '86104',
                'ruang_lingkup' => 'Klinik Pratama Pemerintah',
                'dinas_id' => 2,
                'kategorikbli_id' => 17,
            ],
            [
                'nama' => 'AKTIVITAS KLINIK SWASTA',
                'kode' => '86105',
                'ruang_lingkup' => 'Seluruh Klinik Pratama dan Utama Swasta',
                'dinas_id' => 2,
                'kategorikbli_id' => 17,
            ],
            [
                'nama' => 'AKTIVITAS PELAYANAN KESEHATAN YANG DILAKUKAN OLEH TENAGA KESEHATAN SELAIN DOKTER DAN DOKTER GIGI',
                'kode' => '86901',
                'ruang_lingkup' => 'Griya Sehat',
                'dinas_id' => 2,
                'kategorikbli_id' => 17,
            ],
            [
                'nama' => 'LAB MEDIS KELAS PRATAMA',
                'kode' => '86903',
                'ruang_lingkup' => 'Lab Medis Kelas Pratama',
                'dinas_id' => 2,
                'kategorikbli_id' => 17,
            ],
            [
                'nama' => 'HOTEL BINTANG',
                'kode' => '55110A',
                'ruang_lingkup' => 'Hotel Dengan Luas Bangunan >10.000 M2',
                'dinas_id' => 5,
                'kategorikbli_id' => 22,
            ],
            [
                'nama' => 'HOTEL BINTANG',
                'kode' => '55110B',
                'ruang_lingkup' => 'Hotel dengan Luas Bangunan >6.000 - >10.000 M2',
                'dinas_id' => 5,
                'kategorikbli_id' => 22,
            ],
            [
                'nama' => 'HOTEL MELATI',
                'kode' => '55120A',
                'ruang_lingkup' => 'Hotel dengan Luas Bangunan >10.000 M2',
                'dinas_id' => 5,
                'kategorikbli_id' => 22,
            ],
            [
                'nama' => 'HOTEL MELATI',
                'kode' => '55120B',
                'ruang_lingkup' => 'Hotel dengan Luas Bangunan >6.000 - >10.000 M2',
                'dinas_id' => 5,
                'kategorikbli_id' => 22,
            ],
            [
                'nama' => 'VILA',
                'kode' => '55193',
                'ruang_lingkup' => 'Vila (Bintang 2 dan 3)',
                'dinas_id' => 5,
                'kategorikbli_id' => 22,
            ],
            [
                'nama' => 'APARTEMEN HOTEL',
                'kode' => '55194A',
                'ruang_lingkup' => 'Apartemen Hotel dengan Luas Bangunan >4.000 - <6.000 M2',
                'dinas_id' => 5,
                'kategorikbli_id' => 22,
            ],
            [
                'nama' => 'APARTEMEN HOTEL',
                'kode' => '55194B',
                'ruang_lingkup' => 'Apartemen Hotel dengan Luas Bangunan >6.000 - <10.000 M2',
                'dinas_id' => 5,
                'kategorikbli_id' => 22,
            ],
            [
                'nama' => 'RESTORAN',
                'kode' => '56101A',
                'ruang_lingkup' => 'Restoran dengan jumlah tempat duduk tamu > 200 unit',
                'dinas_id' => 5,
                'kategorikbli_id' => 22,
            ],
            [
                'nama' => 'RESTORAN',
                'kode' => '56101B',
                'ruang_lingkup' => 'Restoran dengan jumlah tempat duduk tamu 101-200 unit',
                'dinas_id' => 5,
                'kategorikbli_id' => 22,
            ],
            [
                'nama' => 'ANGKUTAN BUS KOTA',
                'kode' => '49214',
                'ruang_lingkup' => 'Angkutan Bus Kota Dalam Trayek',
                'dinas_id' => 6,
                'kategorikbli_id' => 9,
            ],
            [
                'nama' => 'ANGKUTAN PERKOTAAN BUKAN BUS, DALAM TRAYEK',
                'kode' => '49413',
                'ruang_lingkup' => 'Angkutan Perkotaan Bukan Bus Dalam Trayek',
                'dinas_id' => 6,
                'kategorikbli_id' => 9,
            ],
            [
                'nama' => 'NGKUTAN DARAT BUKAN BUS UNTUK PENUMPANG LAINNYA, DALAM TRAYEK',
                'kode' => '49419',
                'ruang_lingkup' => 'Angkutan Darat Bukan Bus Untuk Penumpang Lainnya Dalam Trayek',
                'dinas_id' => 6,
                'kategorikbli_id' => 9,
            ],
            [
                'nama' => 'ANGKUTAN TAKSI',
                'kode' => '49421',
                'ruang_lingkup' => 'Angkutan Taksi',
                'dinas_id' => 6,
                'kategorikbli_id' => 9,
            ],
            [
                'nama' => 'ANGKUTAN PENYEBERANGAN DALAM KABUPATEN/KOTA UNTUK PENUMPANG',
                'kode' => '50218',
                'ruang_lingkup' => 'Angkutan Penyeberangan Dalam Kabupaten/Kota Untuk Penumpang',
                'dinas_id' => 6,
                'kategorikbli_id' => 9,
            ],
            [
                'nama' => 'AKTIVITAS PERPARKIRAN DI LUAR BADAN JALAN (OFF STREET PARKING)',
                'kode' => '52215',
                'ruang_lingkup' => 'Aktivitas Perparkiran Di Luar Badan Jalan',
                'dinas_id' => 6,
                'kategorikbli_id' => 9,
            ],
            [
                'nama' => 'PENGUMPULAN AIR LIMBAH TIDAK BERBAHAYA',
                'kode' => '37011',
                'ruang_lingkup' => 'Pengumpulan dan pengangkutan air limbah domestic baik dari rumah tangga maupun usaha dan/atau kegiatan dengan kapasitas ≤5 M3/angkutan dengan menggunakan angkutan/moda pengakut air limbah.',
                'dinas_id' => 9,
                'kategorikbli_id' => 6,
            ],
            [
                'nama' => 'PENGUMPULAN AIR LIMBAH BERBAHAYA',
                'kode' => '37012',
                'ruang_lingkup' => 'Pengumpulan dan pengangkutan air limbah domestic baik dari rumah tangga maupun usaha dan/atau kegiatan dengan kapasitas >5 M3/angkutan dan atau kegiatan untuk semua besaran kapasitas dengan angkutan/moda pengakut air limbah.',
                'dinas_id' => 9,
                'kategorikbli_id' => 6,
            ],
            [
                'nama' => 'TREATMENT DAN PEMBUANGAN AIR LIMBAH BERBAHAYA',
                'kode' => '37022A',
                'ruang_lingkup' => 'Instalasi pengolahan lumpur tinja (PILT) termasu fasilitas penunjangan dengan kapasitas ≥50m3/hari, dan/atau',
                'dinas_id' => 9,
                'kategorikbli_id' => 6,
            ],
            [
                'nama' => 'TREATMENT DAN PEMBUANGAN AIR LIMBAH BERBAHAYA',
                'kode' => '37022B',
                'ruang_lingkup' => 'Instalasi pengolahan air limbah (IPAL) industri',
                'dinas_id' => 9,
                'kategorikbli_id' => 6,
            ],
            [
                'nama' => 'TREATMENT DAN PEMBUANGAN AIR LIMBAH BERBAHAYA',
                'kode' => '37022C',
                'ruang_lingkup' => 'Instalasi pengolahan air limbah (IPAL) terpadu (air limbah domestic dan air limbah proses dari usaha dan/atau kegiatan)',
                'dinas_id' => 9,
                'kategorikbli_id' => 6,
            ],
            [
                'nama' => 'Treatment dan Pembuangan Air Limbah Berbahaya',
                'kode' => '37022D',
                'ruang_lingkup' => 'Instalasi pengolahan air limbah (IPAL) domestik termasuk fasilitas penunjangnya dengan kapasitas melayani ≥20.000 jiwa atau 2.000 m3/hari',
                'dinas_id' => 9,
                'kategorikbli_id' => 6,
            ],
            [
                'nama' => 'TREATMENT DAN PEMBUANGAN LIMBAH DAN SAMPAH TIDAK BERBAHAYA',
                'kode' => '38211A',
                'ruang_lingkup' => 'Pengolahan limbah dan sampah yang tidak berbahaya secara termal dengan/atau tanpa menghasilkan produk berupa Listrik atau uap',
                'dinas_id' => 9,
                'kategorikbli_id' => 6,
            ],
            [
                'nama' => 'TREATMENT DAN PEMBUANGAN LIMBAH DAN SAMPAH TIDAK BERBAHAYA',
                'kode' => '38211B',
                'ruang_lingkup' => 'Pengolahan sampah yang tidak berbahaya menghasilkan produk berupa bahan bakar alternatif/substitusi, biofuel, biogas, dan lainnya (contoh kegiatan pengolahan sampah yang masuk dalam kelompok ini meliputi : fasilitas pengolahan sampah menghasilkan RDF, SRF',
                'dinas_id' => 9,
                'kategorikbli_id' => 6,
            ],
            [
                'nama' => 'PERTANIAN JAGUNG',
                'kode' => '01111A',
                'ruang_lingkup' => 'Usaha budi daya (meliputi antara lain penyediaan saprodi yang tepat, pertanaman, pemeliharaan, panen, dan/atau pascapanen) tanaman jagung',
                'dinas_id' => 8,
                'kategorikbli_id' => 3,
            ],
            [
                'nama' => 'PERTANIAN JAGUNG',
                'kode' => '01111B',
                'ruang_lingkup' => 'Usaha perbenihan jagung',
                'dinas_id' => 8,
                'kategorikbli_id' => 3,
            ],
            [
                'nama' => 'PERTANIAN JAGUNG',
                'kode' => '01111C',
                'ruang_lingkup' => 'Usaha budi daya (meliputi antara lain penyedian saprodi yang tepat, pertanaman, pemeliharaan, panen, dan/atau pascapanen) tanaman gandum',
                'dinas_id' => 8,
                'kategorikbli_id' => 3,
            ],
            [
                'nama' => 'PERTANIAN JAGUNG',
                'kode' => '01111D',
                'ruang_lingkup' => 'Usaha budi daya (meliputi antara lain penyedian saprodi yang tepat, pertanaman, pemeliharaan, panen, dan/atau pascapanen) tanaman gandum',
                'dinas_id' => 8,
                'kategorikbli_id' => 3,
            ],
            [
                'nama' => 'PERTANIAN KEDELAI',
                'kode' => '01113A',
                'ruang_lingkup' => 'Usaha budi daya (meliputi antara lain penyedian saprodi yang tepat, pertanaman, pemeliharaan, panen, dan/atau pascapanen) tanaman kedelai',
                'dinas_id' => 8,
                'kategorikbli_id' => 3,
            ],
            [
                'nama' => 'PERTANIAN KEDELAI',
                'kode' => '01113B',
                'ruang_lingkup' => 'Usaha perbenihan kedelai',
                'dinas_id' => 8,
                'kategorikbli_id' => 3,
            ],
            [
                'nama' => 'PERTANIAN KACANG TANAH',
                'kode' => '01114',
                'ruang_lingkup' => 'Usaha perbenihan kedelai',
                'dinas_id' => 8,
                'kategorikbli_id' => 3,
            ],
            [
                'nama' => 'PERTANIAN KACANG HIJAU',
                'kode' => '01115',
                'ruang_lingkup' => 'Usaha perbenihan kacang hijau',
                'dinas_id' => 8,
                'kategorikbli_id' => 3,
            ],
            [
                'nama' => 'PERTANIAN ANEKA KACANG HORTIKULTURA',
                'kode' => '01116A',
                'ruang_lingkup' => 'Perbenihan aneka kacang hortikultura',
                'dinas_id' => 8,
                'kategorikbli_id' => 3,
            ],
            [
                'nama' => 'PERTANIAN ANEKA KACANG HORTIKULTURA',
                'kode' => '01116B',
                'ruang_lingkup' => 'Budi daya aneka kacang hortikultura',
                'dinas_id' => 8,
                'kategorikbli_id' => 3,
            ],
            [
                'nama' => 'PERTANIAN BIJI-BIJIAN PENGHASIL MINYAK MAKAN',
                'kode' => '01117A',
                'ruang_lingkup' => 'Produk benih wijen',
                'dinas_id' => 8,
                'kategorikbli_id' => 3,
            ],
            [
                'nama' => 'PERTANIAN BIJI-BIJIAN PENGHASIL MINYAK MAKAN',
                'kode' => '01117B',
                'ruang_lingkup' => 'Budi daya wijen',
                'dinas_id' => 8,
                'kategorikbli_id' => 3,
            ],
        ];

        DB::table('kbli')->insert($data);
    }
}